title: "Johann M. Barnard - CV"

compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_picture_tag

# Settings for jekyll_picture_tag:
picture:
  source: images/_fullsize
  output: assets/images/resized

exclude: ["node_modules", "webpack"]
