title: 'Johann M. Barnard - CV'

sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

encoding: 'utf-8'
compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude: ['node_modules', 'webpack']
