name: deploy

# Only trigger when pushing to master:
on:
  push:
    branches:
      - master

# Deploy jobs
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      # Make sure to check out the repo
      - uses: actions/checkout@v3

      - name: Install libvips and associated image-handling libraries
        run: ./install-libvips.sh

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      # Cache Ruby gems to decrease build times
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install npm dependencies
        run: npm ci

      - name: Build webpack part of site (production)
        run: npm run build:prod

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
